POLICIES = [["AdultEducationSubsidies", ad_ed_sb.get(), SLIDERS["default values"]],
        ["AgricultureSubsidies", agri_sb.get(),SLIDERS["default values"]],
        ["AlcoholLaw", alco_sb.get(),SLIDERS["alcohol"]],
        ["ArmedPolice", arm_pol_sb.get(),SLIDERS["armed police"]],
        ["BanSundayShopping", sun_trade_sb.get(), SLIDERS["default values"]],
        ["BiofuelSubsidies", biofuel_sb.get(), SLIDERS["default values"]],
        ["BorderControls", border_sb.get(), SLIDERS["border"]], 
        ["BusLanes", bus_lane_sb.get(), SLIDERS["default values"]],
        ["BusSubsidies", bus_subs_sb.get(), SLIDERS["default values"]],
        ["CarEmmissionsLimits", car_emissions_sb.get(), SLIDERS["default values"]],
        ["CarTax", car_tax_sb.get(), SLIDERS["default values"]], 
        ["CCTVCameras", cctv_sb.get(), SLIDERS["CCTV"]],
        ["ChildBenefit", childcare_sb.get(), SLIDERS["default values"]],
        ["ChildcareProvision", childcare_sb.get(), SLIDERS["default values"]],
        ["CitizenshipTests", citizen_sb.get(), SLIDERS["default values"]],
        ["CleanEnergySubsidies", clean_energy_sb.get(), SLIDERS["default values"]],
        ["CleanFuelSubsidy", clean_fuel_sb.get(), SLIDERS["default values"]],
        ["CommunityPolicing", com_pol_sb.get(), SLIDERS["default values"]],
        ["ConsumerRights", consumer_rts_sb.get(), SLIDERS["consumer"]],
        ["Creationism", creationism_sb.get(), SLIDERS["creation"]],
        ["Curfews", curfews_sb.get(), SLIDERS["curfews"]],
        ["DeathPenalty", death_pen_sb.get(), SLIDERS["death"]],
        ["DetentionWithoutTrial", detention_sb.get(), SLIDERS["detention"]],
        ["DisabilityBenefit", disability_sb.get(), SLIDERS["detention"]],
        ["FaithSchoolSubsidies", faith_schools_sb.get(), SLIDERS["default values"]],
        ["ForeignAid", foreign_aid_sb.get(), SLIDERS["default values"]],
        ["FreeBusPasses", bus_passes_sb.get(), SLIDERS["default values"]],
        ["FreeEyeTests", eye_tests_sb.get(), SLIDERS["default values"]],
        ["FreeSchoolMeals", school_meals_sb.get(), SLIDERS["default values"]],
        ["Gambling", gambling_sb.get(), SLIDERS["gambling"]], 
        ["GatedCommunities", gated_sb.get(), SLIDERS["gated"]],
        ["GraduateTax", grad_tax_sb.get(), SLIDERS["default values"]],
        ["HandgunLaws", handgun_sb.get(), SLIDERS["handguns"]],
        ["HybridCarsInitiative", hybrid_sb.get(), SLIDERS["default values"]],
        ["IDCards", id_sb.get(), SLIDERS["id"]],
        ["ImportTarrifs", tariffs_sb.get(), SLIDERS["default values"]],
        ["IntelligenceServices", intel_sb.get(), SLIDERS["intel"]],
        ["InternetCensorship", internet_censorship_sb.get(), SLIDERS["net censorship"]],
        ["JuryTrial", jury_trial_sb.get(), SLIDERS["jury trial"]],
        ["LabourLaws", labor_laws_sb.get(), SLIDERS["labor laws"]],
        ["LegalAid", legal_aid_sb.get(), SLIDERS["default values"]],
        ["LegaliseProstitution", prostitution_sb.get(), SLIDERS["default values"]],
        ["MarriedTaxAllowance", married_tax_sb.get(), SLIDERS["marrage tax"]],
        ["MaternityLeave", maternity_sb.get(), SLIDERS["maternity"]],
        ["MicrogenerationGrants", microgen_grants_sb.get(), SLIDERS["default values"]],
        ["MilitarySpending", military_sb.get(), SLIDERS["military"]],
        ["Monorail", monorail_sb.get(), SLIDERS["default values"]],
        ["MortgageTaxRelief", mortgage_relief_sb.get(), SLIDERS["default values"]],
        ["Narcotics", narcotics_sb.get(), SLIDERS["narcotics"]],
        ["NationalService", national_service_sb.get(), SLIDERS["national service"]],
        ["OrganDonation", organ_donor_sb.get(), SLIDERS["organs"]],
        ["OrganicSubsidy", organic_farm_sb.get(), SLIDERS["default values"]],
        ["PhoneTapping", wire_tapping_sb.get(), SLIDERS["wire tap"]], 
        ["PlasticBagTax", plas_bag_sb.get(), SLIDERS["default values"]],
        ["PoliceForce", police_sb.get(), SLIDERS["default values"]],
        ["PollutionControls", pollution_sb.get(), SLIDERS["pollution"]],
        ["PrisonerTagging", pris_tag_sb.get(), SLIDERS["default values"]],
        ["Prisons", prisons_sb.get(), SLIDERS["prison"]],
        ["PublicLibraries", libraries_sb.get(), SLIDERS["default values"],
        ["RacialProfiling", profiling_sb.get(), SLIDERS["default values"]],
        ["RaceDiscriminationAct", discrimination_sb.get(), SLIDERS["default values"]],
        ["RailSubsidies", rail_subs_sb.get(), SLIDERS["default values"]],
        ["Recycling", recycling_sb.get(), SLIDERS["recycling"]],
        ["RoadBuilding", roads_sb.get(), SLIDERS["roads"]],
        ["RuralDevelopmentGrants", rural_dev_sb.get(), SLIDERS["default values"]],
        ["SateliteRoadPricing", sat_rd_sb.get(), SLIDERS["default values"]],
        ["SchoolBuses", sub_sch_bus_sb.get(), SLIDERS["default values"]],
        ["SchoolPrayers", prayer_sb.get(),SLIDERS["prayer"]],
        ["ScienceFunding", science_sb.get(),SLIDERS["science"]],
        ["SmallBusinessGrants", small_business_sb.get(), SLIDERS["default values"]],
        ["SpaceProgram", space_sb.get(), SLIDERS["space"]],
        ["SpeedCameras", speed_sb.get(), SLIDERS["speed"]],
        ["StateHealthService", health_sb.get(), SLIDERS["health"]],
        ["StateHousing", housing_sb.get(), SLIDERS["default values"]],
        ["StatePensions", pension_sb.get(), SLIDERS["default values"]],
        ["StateSchools", sschools_sb.get(), SLIDERS["schools"]],
        ["StemCells", stem_cell_sb.get(), SLIDERS["default values"]],
        ["TaxShelters", tax_shelter_sb.get(), SLIDERS["default values"]], 
        ["TechnologyColleges", tech_college_sb.get(), SLIDERS["default values"]],
        ["TechnologyGrants", tech_grant_sb.get(), SLIDERS["default values"]],
        ["TelecommutingInitiative", telecommute_sb.get(), SLIDERS["default values"]],
        ["TollRoads", toll_road_sb.get(), SLIDERS["default values"]],
        ["UnemployedBenefit", unemployment_sb.get(), SLIDERS["default values"]],
        ["UniversityGrants", university_sb.get(), SLIDERS["uni"]],
        ["WelfareFraudDept", wel_fraud_sb.get(), SLIDERS["welfare"]],
        ["WinterFuelSubsidy", winter_fuel_sb.get(), SLIDERS["default values"]],
        ["WorkSafetyLaw", work_safe_sb.get(), SLIDERS["default values"]],
        ["YouthClubSubsidies", youth_club_sb.get(), SLIDERS["default values"]],
        ["AbortionLaw", abortion_sb.get(), SLIDERS["abortion"]],
        ["RentControls", rent_cont_sb.get(), SLIDERS["default values"]],
        ["SchoolVouchers", school_vouch_sb.get(), SLIDERS["default values"]],
        ["OilDrillingSubsidy", oil_drilling_sb.get(), SLIDERS["default values"]],
        ["MansionTax", mansion_sb.get(), SLIDERS["default values"]],
        ["FuelEfficiency", fuel_eff_sb.get(), SLIDERS["default values"]],
        ["ForeignInvestorTaxBreaks", for_invest_sb.get(), SLIDERS["default values"]],
        ["RoboticsResearch", robot_research_sb.get(), SLIDERS["default values"]],
        ["PrivatePrisons", prov_pris_sb.get(), SLIDERS["default values"]], 
        ["HealthFoodSubsidies", health_food_sb.get(), SLIDERS["default values"]],
        ["Tasers", tasers_sb.get(), SLIDERS["default values"]],
        ["PoliceDrones", police_drones_sb.get(), SLIDERS["default values"]],
        ["ArtsSubsidies", art_sub_sb.get(), SLIDERS["arts"]],
        ["HealthcareVouchers", health_food_sb.get(), SLIDERS["default values"]],
        ["HealthTaxCredits", health_tax_sb.get(), SLIDERS["default values"]],
        ["SchoolTaxCredits", school_tax_sb.get(), SLIDERS["default values"]],
        ["FoodStamps", food_stamps_sb.get(), SLIDERS["default values"]],
        ["FoodStandards", food_stand_sb.get(), SLIDERS["default values"]],
        ["EnterpriseInvestmentScheme", ent_invest_sb.get(), SLIDERS["default values"]],
        ["RecreationalDrugsTax", rec_drug_tax_sb, SLIDERS["default values"]]]]

with open("policies.txt", 'w') as file:
    file.write(str(POLICIES))



TAXES = [["AirlineTax", airline_tax_sb.get()],
    ["AlcoholTax", alco_tax_sb.get()],
    ["CarbonTax", carbon_tax_sb.get()],
    ["CorporationTax", corp_tax_sb.get()], 
    ["IncomeTax", income_tax_sb.get()],
    ["FlatTax", flat_income_tax_sb.get()],
    ["CapitalGainsTax", cap_gains_sb.get()],
    ["InheritanceTax", inheritance_tax_sb.get()],
    ["InternetTax", internet_tax_sb.get()],
    ["LuxuryGoodsTax", luxary_tax_sb.get()], 
    ["PetrolTax", petrol_tax_sb.get()],
    ["PropertyTax", prop_tax_sb.get()],
    ["SalesTax", sales_tax_sb.get()],
    ["TobaccoTax", tobac_tax_sb.get()],
    ["JunkFoodTax", junk_food_sb.get()]]















